version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore(deps):"
    versioning-strategy: "increase"
    # Grouper les PRs par type
    groups:
      # Groupe 1 : Mises à jour de sécurité - 1 PR
      security:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
          - "major"
      # Groupe 2 : Mises à jour mineures et patches - 1 PR
      minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Groupe 3 : Mises à jour majeures - Une PR par package
      major:
        dependency-type: "production"
        update-types:
          - "major"

  # Configuration pour GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "ci(actions):"
